[toolchain]
anchor_version = "0.30.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_dapp = "CMTzqVU6BRtBLWzDvkrXhHcT2ZvJteKydwZ29LkwrYmJ"

[programs.devnet]
todo_dapp = "CMTzqVU6BRtBLWzDvkrXhHcT2ZvJteKydwZ29LkwrYmJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
